// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAItwUK_Ey1wX5JwNrRUEph_MXJ82Fj_Q',
    appId: '1:176959158559:web:ef1c45290ed1c43f29582a',
    messagingSenderId: '176959158559',
    projectId: 'chat-app-94b4d',
    authDomain: 'chat-app-94b4d.firebaseapp.com',
    storageBucket: 'chat-app-94b4d.appspot.com',
    measurementId: 'G-EB7GBF859C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXy3wGetoNB_DMXDt1FAg0cHCmwIU4k4Q',
    appId: '1:176959158559:android:d714efdcc3c1a70029582a',
    messagingSenderId: '176959158559',
    projectId: 'chat-app-94b4d',
    storageBucket: 'chat-app-94b4d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJEyXKP1nWwzR9QJQKpsTO2qz5KHRLXg',
    appId: '1:176959158559:ios:d74de9156ef4192029582a',
    messagingSenderId: '176959158559',
    projectId: 'chat-app-94b4d',
    storageBucket: 'chat-app-94b4d.appspot.com',
    iosClientId:
        '176959158559-das0eqlc0oshrpmd8ikc314lnqjjs7fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
